package com.example.demo;

import com.example.demo.service.MyService;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan("com.example.demo.mapper")
public class MainApplication implements CommandLineRunner {

    private final ApplicationContext context;

    // 下次抄代码发现
    public MainApplication(ApplicationContext context) {
        this.context = context;
    }


    public static void main(String[] args) {
        SpringApplication.run(MainApplication.class, args);
        System.out.println("Hello World!");
    }

    @Override
    public void run(String... args) throws Exception {
        MyService myService = context.getBean(MyService.class);

//        myService.doSomething();
//        myService.doSomething2();
//        myService.doSomething3(); // 每次调用都将获取一个新的 PrototypeBean 实例
    }
}
